package org.jeecg.modules.system.enums.tspoints;

/** 积分域机器错误码。 */
public enum TsPointsErrorCode {
    POINTS_NOT_ENOUGH,
    POINTS_ACCOUNT_NOT_FOUND,
    POINTS_TRANSACTION_NOT_FOUND,
    POINTS_DUPLICATE_REQUEST,
    POINTS_REFUND_EXCEEDED,
    POINTS_INVALID_AMOUNT,
    POINTS_BIZ_TYPE_INVALID,
    POINTS_ORDER_STATUS_INVALID,
    POINTS_PRODUCT_NOT_FOUND,
    POINTS_PAYMENT_NOT_FOUND,
    POINTS_PAYMENT_CALLBACK_INVALID
}
