services:
  jeecg-boot-mysql:
    image: mysql:8.0
    restart: always
    container_name: jeecg-boot-mysql
    hostname: jeecg-boot-mysql
    ports:
      - ${MYSQL_PORT}:3306
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
    command: ["--lower_case_table_names=1"]
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - share-net

  jeecg-boot-redis:
    image: redis:7-alpine
    ports:
      - ${REDIS_PORT}:6379
    restart: always
    container_name: jeecg-boot-redis
    hostname: jeecg-boot-redis
    env_file:
      - ./.env
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - share-net

  jeecg-boot-kafka:
    image: apache/kafka:4.0.0
    restart: always
    container_name: jeecg-boot-kafka
    hostname: jeecg-boot-kafka
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://jeecg-boot-kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@jeecg-boot-kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 6
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    networks:
      - share-net

  jeecg-boot-system:
    build:
      context: ./system
    restart: on-failure
    container_name: jeecg-boot-system
    image: jeecg-boot-system
    hostname: jeecg-boot-system
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - jeecg-boot-mysql
      - jeecg-boot-redis
      - jeecg-boot-kafka
    networks:
      - share-net

networks:
  share-net:
    name: share-net
