package org.jeecg.modules.system.enums.tsactivity;

/** 活动域机器错误码。 */
public enum TsActivityErrorCode {
    ACTIVITY_TASK_NOT_FOUND,
    ACTIVITY_TASK_NOT_ACTIVE,
    ACTIVITY_PROGRESS_NOT_FOUND,
    ACTIVITY_TASK_NOT_COMPLETED,
    ACTIVITY_REWARD_NOT_FOUND,
    ACTIVITY_REWARD_TYPE_UNSUPPORTED,
    ACTIVITY_INVALID_ARGUMENT,
    ACTIVITY_CONFIGURATION_INVALID
}
