SERVER_PORT=7008

DRUID_LOGIN_USERNAME=admin
DRUID_LOGIN_PASSWORD=123456

MYSQL_URL=jdbc:mysql://localhost:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
MYSQL_USERNAME=root
MYSQL_PASSWORD=gzx635764803

REDIS_DATABASE=0
REDIS_HOST=117.72.149.125
REDIS_PORT=6379
REDIS_PASSWORD=Aaa635764803


UPLOAD_TYPE=minio
R2_ENDPOINT=https://oss.6357648.xyz
R2_ACCESS_KEY_ID=fb104242065d9093a7f535cd367bf187
R2_SECRET_ACCESS_KEY=2374960dd85bc91072f58bf8d15ddc341934eecc6b005d36459720e054710b99
R2_TOKEN=ZN20M_WgRW-l-r-H1j2lBSnwchnQJSM_XP2dZCnV
R2_BUCKET_NAME=ai-company-image
R2_PUBLIC_DOMAIN=https://oss.6357648.xyz


EMBED_STORE_HOST=localhost
EMBED_STORE_PORT=15432
EMBED_STORE_DATABASE=postgres
EMBED_STORE_USER=postgres
EMBED_STORE_PASSWORD=123456
EMBED_STORE_TABLE=embeddings

MANAGEMENT_ENDPOINTS_EXPOSURE=health,info,metrics,prometheus
MANAGEMENT_HEALTH_SHOW_DETAILS=when_authorized
