CREATE TABLE IF NOT EXISTS `ts_ai_log` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `trace_id` varchar(64) NOT NULL COMMENT '调用链追踪ID',
  `user_id` varchar(64) DEFAULT NULL COMMENT '用户ID',
  `username` varchar(100) DEFAULT NULL COMMENT '用户名',
  `biz_type` varchar(32) DEFAULT NULL COMMENT '业务类型：role/story/chat',
  `biz_scene` varchar(64) DEFAULT NULL COMMENT '业务场景',
  `endpoint` varchar(255) NOT NULL COMMENT '接口路径',
  `http_method` varchar(16) DEFAULT NULL COMMENT 'HTTP方法',
  `controller_method` varchar(255) DEFAULT NULL COMMENT '控制器方法',
  `request_params` longtext COMMENT '请求参数摘要',
  `provider` varchar(64) DEFAULT NULL COMMENT '模型供应商',
  `model_name` varchar(128) DEFAULT NULL COMMENT '模型名称',
  `model_id` varchar(64) DEFAULT NULL COMMENT '模型ID',
  `prompt_code` varchar(128) DEFAULT NULL COMMENT '首轮提示词模板编码',
  `prompt_version` varchar(32) DEFAULT NULL COMMENT '首轮提示词模板版本',
  `repair_prompt_code` varchar(128) DEFAULT NULL COMMENT '修复提示词模板编码',
  `repair_prompt_version` varchar(32) DEFAULT NULL COMMENT '修复提示词模板版本',
  `has_repair` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否触发JSON修复',
  `status` varchar(32) NOT NULL DEFAULT 'running' COMMENT '执行状态：running/success/failed',
  `cost_ms` bigint DEFAULT NULL COMMENT '总耗时ms',
  `error_message` longtext COMMENT '错误信息',
  `final_result_json` longtext COMMENT '最终结果JSON',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_ts_ai_log_trace_id` (`trace_id`),
  KEY `idx_ts_ai_log_endpoint` (`endpoint`),
  KEY `idx_ts_ai_log_biz_scene` (`biz_scene`),
  KEY `idx_ts_ai_log_status` (`status`),
  KEY `idx_ts_ai_log_has_repair` (`has_repair`),
  KEY `idx_ts_ai_log_provider_model` (`provider`,`model_name`),
  KEY `idx_ts_ai_log_prompt` (`prompt_code`,`prompt_version`),
  KEY `idx_ts_ai_log_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='ts AI调用监控主表';

CREATE TABLE IF NOT EXISTS `ts_ai_log_step` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `log_id` bigint NOT NULL COMMENT '主日志ID',
  `trace_id` varchar(64) NOT NULL COMMENT '调用链追踪ID',
  `step_no` int NOT NULL COMMENT '步骤序号',
  `step_type` varchar(64) NOT NULL COMMENT '步骤类型',
  `step_name` varchar(128) DEFAULT NULL COMMENT '步骤名称',
  `status` varchar(32) NOT NULL DEFAULT 'success' COMMENT '步骤状态：success/failed',
  `prompt_code` varchar(128) DEFAULT NULL COMMENT '步骤命中模板编码',
  `prompt_version` varchar(32) DEFAULT NULL COMMENT '步骤命中模板版本',
  `provider` varchar(64) DEFAULT NULL COMMENT '模型供应商',
  `model_name` varchar(128) DEFAULT NULL COMMENT '模型名称',
  `model_id` varchar(64) DEFAULT NULL COMMENT '模型ID',
  `developer_prompt` longtext COMMENT 'developer_prompt',
  `user_prompt` longtext COMMENT 'user_prompt',
  `tool_schema` longtext COMMENT 'tool_schema',
  `rendered_prompt` longtext COMMENT '渲染后的完整Prompt',
  `request_payload_json` longtext COMMENT '真实发送请求摘要JSON',
  `response_raw` longtext COMMENT '模型原始返回',
  `response_json` longtext COMMENT '解析后的JSON',
  `validation_issues` longtext COMMENT '校验或修复问题摘要',
  `final_output_json` longtext COMMENT '步骤最终输出',
  `extra_info_json` longtext COMMENT '额外扩展信息',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_ts_ai_log_step_log_id` (`log_id`),
  KEY `idx_ts_ai_log_step_trace_id` (`trace_id`),
  KEY `idx_ts_ai_log_step_type` (`step_type`),
  KEY `idx_ts_ai_log_step_create_time` (`create_time`),
  CONSTRAINT `fk_ts_ai_log_step_log_id` FOREIGN KEY (`log_id`) REFERENCES `ts_ai_log` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='ts AI调用监控步骤表';
