CREATE TABLE IF NOT EXISTS `ts_agent_chat_message_event` (
  `id` varchar(64) NOT NULL COMMENT '事件ID',
  `message_id` bigint NOT NULL COMMENT '触发当前Run的用户消息ID',
  `session_id` bigint NOT NULL COMMENT 'Agent会话ID',
  `agent_session_id` bigint DEFAULT NULL COMMENT 'Agent会话记录ID',
  `run_id` varchar(64) DEFAULT NULL COMMENT 'Agent运行ID',
  `trace_id` varchar(64) DEFAULT NULL COMMENT '链路追踪ID',
  `parent_run_id` varchar(64) DEFAULT NULL COMMENT '父运行ID',
  `parent_event_id` varchar(64) DEFAULT NULL COMMENT '父事件ID',
  `turn_id` varchar(64) DEFAULT NULL COMMENT '对话轮次ID',
  `sender_type` varchar(32) DEFAULT NULL COMMENT '发送方类型',
  `agent_code` varchar(64) DEFAULT NULL COMMENT 'Agent编码',
  `type` varchar(16) NOT NULL COMMENT '事件类型：subagent/tool',
  `name` varchar(128) NOT NULL COMMENT 'SubAgent或Tool名称',
  `content` text DEFAULT NULL COMMENT '结果摘要',
  `status` tinyint DEFAULT NULL COMMENT '状态：1成功 0失败 2运行中或未知',
  `json` longtext DEFAULT NULL COMMENT '完整执行JSON：input/output/error/metrics',
  `is_deleted` tinyint NOT NULL DEFAULT 0 COMMENT '是否删除：0否 1是',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_ts_agent_chat_message_event_message_id` (`message_id`),
  KEY `idx_ts_agent_chat_message_event_session_id` (`session_id`),
  KEY `idx_ts_agent_chat_message_event_run_id` (`run_id`),
  KEY `idx_ts_agent_chat_message_event_trace_id` (`trace_id`),
  KEY `idx_ts_agent_chat_message_event_parent_event_id` (`parent_event_id`),
  KEY `idx_ts_agent_chat_message_event_type_name` (`type`, `name`),
  KEY `idx_ts_agent_chat_message_event_agent` (`agent_code`, `sender_type`),
  KEY `idx_ts_agent_chat_message_event_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent聊天消息完整执行事件表';
