MYSQL_URL=jdbc:mysql://jeecg-boot-mysql:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
MYSQL_USERNAME=root
MYSQL_PASSWORD=gzx635764803

REDIS_HOST=jeecg-boot-redis
REDIS_PORT=6379
REDIS_PASSWORD=Aaa635764803

CHAT_EXECUTOR_BASE=http://fastapi-langgraph:8000
